### ISSUE TITLE
[Question] Any way to avoid to create show action for create action?

### ISSUE THREAD

**Issue by takashi** [cookpad/garage#37]
I created this controller 

```ruby
class UsersController < ApplicationController
  include Garage::RestfulActions

  def require_resources
    @resources = User.all
  end

  def require_resource
    @resource = User.find(params[:id])
  end

  def create_resource
    @resources.create(user_params)
  end

  private

  def user_params
    params
      .require(:user)
      .permit(:first_name, :last_name, :first_name_kana, :last_name_kana,
              :email, :password, :password_confirmation, :birthday, :sex)
  end
end
```

and routing 

```ruby
resources :users, only: [:index, :show, :create]
```

it works well, but if I don't want to provide and remove `show` action from routing, error occured like `No route matches {:action=>"show", :controller=>"users", :id=>4}` when i call create action. because of [this line](https://github.com/cookpad/garage/blob/master/lib/garage/restful_actions.rb#L215-L217)

There is any way to remove show action but using create action?

Thanks.

**Comment by taiki45** [comment]
Garage is designed to lead RESTful API which shows created resource in show action.

If you go off the Garage way, simply overwrite `location` method in your controller like:

```ruby
  def location
    {}
  end
```

**Comment by takashi** [comment]
@taiki45 thanks for your information ! I'll close this issue

**Comment by kenchan0130** [comment]
I stumbled on this part too.
We are not always location that is show action of resource.
You might want to comment on that method.
