### ISSUE TITLE
Please replace YOURNAME by copyright holder's name in license file

### ISSUE THREAD

**Issue by Screwland** [cookpad/garage#49]
In MIT-LICENSE File,
```
Copyright 2013 YOURNAME
```
YOURNAME is NOT human's name.
Please replace YOURNAME by copyright holder's name.

**Comment by sorah** [comment]
ooh, good point. I didn't notice it...

@cookpad/garage I'd like to write COOKPAD Inc. here. I'll commit later if there's no concern

**Comment by taiki45** [comment]
Oh, good catch.

@sorah Looks good to me.

**Comment by taiki45** [comment]
done ea92abf

**Comment by Screwland** [comment]
Very Good.
