### ISSUE TITLE
How to add extra actions?

### ISSUE THREAD

**Issue by evnton** [cookpad/garage#65]
I want to add extra actions(except :index, :create, :show, :update, :destroy), when used garage in my project, something like "/v1/users/get_names".

How to do that?

**Comment by taiki45** [comment]
I don't know your requirements, but in general, you can:

1. Routes `/v1/users/get_names` to `UserNamesController#index` or something.
2. Define extra actions to your controller like this: https://github.com/cookpad/garage/blob/a0184a662f076323d7bee259f3f2d1c229a734aa/spec/dummy/app/controllers/posts_controller.rb#L10-L12
