### ISSUE TITLE
doorkeeper dependency

### ISSUE THREAD

**Issue by supermomonga** [cookpad/garage#9]
I read @taiki45's [this post](http://techlife.cookpad.com/entry/2014/11/06/100000) and the post describes about doorkeeper dependency as following.

>Doorkeeper は Rails アプリケーションに OAuth 2 provider の機能を持たせるための gem です。Garage は Doorkeeper を用いて認可機能を提供します。
>
>クックパッドでは複数の Garage アプリケーションが存在しているので、>Doorkeeper を使用せずに、認証認可サーバーへ認証認可を委譲するモジュールを >Garage に追加しています。このような Doorkeeper 以外の認可実装や認可を行わない実装への対応は Garage 本体へ追加予定です。

Is there any roadmap or schedules about this?

**Comment by taiki45** [comment]
Sorry for late response. This issue seems to be solved by https://github.com/cookpad/garage/pull/24 and released as v1.5.0.

Please re-open this issue if you have anything about this.

**Comment by supermomonga** [comment]
yay! thanks ;)
